---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R libs $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp .DS_Store $DEPLOYPATH
    - /bin/cp CNAME $DEPLOYPATH
    - /bin/cp LICENSE.MD $DEPLOYPATH
    - /bin/cp README.MD $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp gulpfire.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
